// leave off @2x/@3x
const images = {
  opening: require('../Images/opening.jpg'),
  mooimomLogo: require('../Images/mooimom-logo.png'),
  mooimomLogoWhite: require('../Images/mooimom-logo-white.png'),
  homeBG: require('../Images/home_bg.png'),
  account: require('../Images/Icons/account.png'),
  category: require('../Images/Icons/category.png'),
  home: require('../Images/Icons/home.png'),
  learn: require('../Images/Icons/learn.png'),
  order: require('../Images/Icons/order.png'),
  shoppingCart: require('../Images/Icons/shopping-cart.png'),
  shoppingCartBlack: require('../Images/Icons/shopping-cart-black.png'),
  wishlist: require('../Images/Icons/wishlist.png'),
  wishlistBlack: require('../Images/Icons/wishlist-black.png'),
  wishlistProduct: require('../Images/Icons/wishlist-2.png'),
  isWishlistProduct: require('../Images/Icons/wishlist-3.png'),
  search: require('../Images/Icons/search.png'),
  notif: require('../Images/Icons/notif.png'),
  notifWhite: require('../Images/Icons/notif-white.png'),
  back: require('../Images/Icons/back.png'),
  whatsapp: require('../Images/Icons/wa.png'),
  facebook: require('../Images/Icons/fb-icon-2.png'),
  instagram: require('../Images/Icons/ig.png'),
  sizeGuide: require('../Images/Icons/size-guide.png'),
  rightArrow: require('../Images/Icons/icon_right_arrow.png'),

  //// TEMP:
  catMasaKehamilan: require('../Images/Icons/masa-kehamilan.png'),
  catMasaMenyusui: require('../Images/Icons/masa-menyusui.png'),
  catPascaMelahirkan: require('../Images/Icons/pasca-melahirkan.png'),
  catProdukBayi: require('../Images/Icons/produk-bayi.png'),
  catGiftSet: require('../Images/Icons/gift-set.png'),
  banner1: require('../Images/temp/banner-1.png'),
  banner2: require('../Images/temp/banner-2.png'),
  banner3: require('../Images/temp/banner-3.png'),
  promo1: require('../Images/temp/promo-1.png'),
  promo2: require('../Images/temp/promo-2.png'),
  promo3: require('../Images/temp/promo-3.png'),
  product1: require('../Images/temp/product-1.jpg'),
  product2: require('../Images/temp/product-2.jpg'),
  product3: require('../Images/temp/product-3.jpg'),
  product4: require('../Images/temp/product-4.jpg'),
}

export default images
