# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def shared_pods
  pod 'MidtransCoreKit'
  pod 'MidtransKit'
end
target 'mooimom' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport',
    'CxxBridge',
  ]
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'QBImagePickerController', :path => '../node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePickerController.podspec'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  shared_pods


  pod 'react-native-config', :path => '../node_modules/react-native-config'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
          if target.name == "React"
              target.remove_from_project
          end
          if target.name == "yoga"
              target.remove_from_project
          end
      end
  end

end
